### ISSUE TITLE
locate_credentials

### ISSUE THREAD

**Issue by twgardner2** [cloudyr/aws.sns#5]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

The docs make 4 references to a `locate_credentials` function (three references to "see `locate_credentials`" in the `snsHTTP` function, and one in the index), but there is no `locate_credentials` function in the docs and doesn't appear to be a `locate_credentials` function in the package.

**Comment by leeper** [comment]
It's in [aws.signature](https://cran.r-project.org/web/packages/aws.signature/index.html). The docs should link to the function.
