### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.sns#6]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by JeffreyStrahm** [comment]
Could you please apply a open source license or some forum of license to it? With a open source license people would be allowed to pick up the project.

EDIT: to elaborate, right now no one even has the right to use this program.

**Comment by antoine-sachet** [comment]
@leeper I have been using `aws.sns` and I don't mind taking over as maintainer - I already maintain a few of your aws packages (`aws.polly`, `aws.comprehend`, `aws.transcribe`, `aws.translate`).

@JeffreyStrahm The package is under GPL (>=2). The license is listed in the DESCRIPTION file as is standard for R packages.

Thanks - Antoine

**Comment by antoine-sachet** [comment]
By the way it is not installable as is since there is no maintainer listed.

```
> remotes::install_github("cloudyr/aws.sns")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo cloudyr/aws.sns@HEAD
✔  checking for file ‘/private/var/folders/hw/8fjjz0qj1xb8w6n2wb20jlpw0000gn/T/RtmpAtoQBI/remotes1520a3ee6da2c/cloudyr-aws.sns-78ab6eb/DESCRIPTION’ ...
─  preparing ‘aws.sns’:
E  checking DESCRIPTION meta-information
   Authors@R field gives no person with maintainer role, valid email
   address and non-empty name.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'aws.sns' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/hw/8fjjz0qj1xb8w6n2wb20jlpw0000gn/T/RtmpAtoQBI/remotes1520a3ee6da2c/cloudyr-aws.sns-78ab6eb/DESCRIPTION’ ... OK
E> * preparing ‘aws.sns’:
E> * checking DESCRIPTION meta-information ... ERROR
E> Authors@R field gives no person with maintainer role, valid email
E> address and non-empty name.
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
```

**Comment by antoine-sachet** [comment]
@MarkEdmondson1234 

I'd like to take over this package to put it back in production, like I did for aws.polly, aws.translate, aws.comprehend, etc. I've got a PR ready to that effect (#8).

Sorry to ping you directly but I think it's the only way :)

**Comment by MarkEdmondson1234** [comment]
Yes its the best way, I don't get the notifications otherwise :)  Have added you, thanks!
