### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by JeffreyStrahm** [cloudyr/aws.sns#7]
This looks like a fantastic and useful project that is currently unable to be used by anyone. Right now, since there is no license, there is no way for anyone to pickup and continue the project and there is no way for anyone to use the project, since it is all protected by copyright. If what I read is correct, the two contributors couldn't even use it as they would be using the others code illegally unless the other gave them permission.

Could you please add a license to this, so that people can use this?

**Comment by leeper** [comment]
It's GPL-2. R package licenses are described in the DESCRIPTION file: https://github.com/cloudyr/aws.sns/blob/master/DESCRIPTION

This package is also not actively maintained.

**Comment by JeffreyStrahm** [comment]
Please formally add the license to the project so it is a lot more obvious to anyone who looks at this.
